spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
   
       
spring.datasource.platform: mysql 
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
spring.datasource.url: jdbc:mysql://localhost/sample?serverTimezone=UTC
